---
permalink: install-linux/task_download_unified_manager.html 
sidebar: sidebar 
keywords: download, Unified Manager 
summary: 'Unified Managerをダウンロードする必要があります `.zip` ファイルをNetApp Support Site から選択して、Unified Managerをインストールします。' 
---
= Unified Manager をダウンロードしています
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Managerをダウンロードする必要があります `.zip` ファイルをNetApp Support Site から選択して、Unified Managerをインストールします。

* 必要なもの *

NetApp Support Siteのログインクレデンシャルが必要です。

ダウンロードする Unified Manager のインストールパッケージは、 Red Hat Enterprise Linux と CentOS の両方のシステムで共通です。

.手順
. NetApp Support Siteにログインし、 Unified Manager のダウンロードページに移動します。
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["NetApp Support Site"]

. 必要なバージョンの Unified Manager を選択し、エンドユーザライセンス契約（ EULA ）に同意します。
. Linux用のUnified Managerインストーラファイルをダウンロードし、を保存します `.zip` ファイルをターゲットシステム上のディレクトリにコピーします。
+
[NOTE]
====
使用している Red Hat Enterprise Linux システムに対応した正しいバージョンのインストーラファイルをダウンロードしていることを確認してください。Red Hat Enterprise Linux 7または8がインストールされているかどうかに基づいて、適切なバージョンのUnified Managerをダウンロードします `.zip` ファイル。

====
. チェックサムを確認して、ソフトウェアが正しくダウンロードされたことを確認します。

